### PR TITLE
BCMOHAD-13389-v1 ||Changed the position of filed on layout

### PR DESCRIPTION
**Pull request by ahshaik1**
Changed the position of filed on layout

### CODE REVIEW

**Comment by cgiSunilM** [comment]
> Changed the position of filed on layout

@ahshaik1, if we only changed the position of the field, then why are actions showing differences? Can you check once? You PR should only indicate the difference for the field and not the actions.

**Review by cgiSunilM — CHANGES_REQUESTED** [review]
@ahshaik1, if we only changed the position of the field, then why are actions showing differences? Can you check once? You PR should only indicate the difference for the field and not the actions.

**Comment by ahshaik1** [comment]
> @ahshaik1, if we only changed the position of the field, then why are actions showing differences? Can you check once? You PR should only indicate the difference for the field and not the actions.

@cgiSunilM I have done the needed changes

**Review by cgiSunilM — APPROVED** [review]
LGTM!

**Pull request merged**
