### PR TITLE
BCMOHAD-26507  || ICY - Create Custom Metadata For Phase 3 Communities

### PR DESCRIPTION
**Pull request by Nikhiljeenru**
# Description
 The existing custom metadata from Prod is added to the GitHub to align with the Live Prod environment.
new 8 regions custom metadata is added as well.

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# List high-level changes as bullet items
The existing custom metadata from Prod is added to the GitHub to align with the Live Prod environment.
new 8 regions custom metadata is added as well.

Below are some examples

- [ ] Changed field permissions
- [ ] changed field data-type

# Deployment Tracker

List all the metadata that is pushed in this commit/PR. Full URL should be fine.

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by cgijeffolsen — APPROVED** [review]
This is as expected. Validation and testing of this PR in SOSE-QA is highly recommended. @lovychauhanCGI @NikhilJeenru01 @NataliaNikishina

**Comment by Nikhiljeenru** [comment]
@cgijeffolsen  I have added some missing changes regarding the field lengths in custom metadata that needs to be extended from 40 to 80 characters in length.

**Review by RanadheerRG — APPROVED** [review]
Reviewed the changes
@Nikhiljeenru  Approved

**Review by lovychauhanCGI — APPROVED** [review]
Changes as expected

**Review by NataliaNikishina — CHANGES_REQUESTED** [review]
@Nikhiljeenru  It is recommended to create a dev-app-post folder and move the CustomMetadata to it to make sure there is no unintended dependency during package creation process. Please also update the title of PR with the corresponding description. Thank you
cc: @cgijeffolsen @RanadheerRG

**Review by NataliaNikishina — APPROVED** [review]
@Nikhiljeenru approved. Thank you!

**Pull request merged**
