### PR TITLE
Permission set update

### PR DESCRIPTION
**Pull request by mhussaincgi**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# List high-level changes as bullet items

Below are some examples

- [ ] Changed field permissions
- [ ] changed field data-type

# Deployment Tracker

List all the metadata that is pushed in this commit/PR. Full URL should be fine.

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by cgijeffolsen — APPROVED** [review]
Approved the removal of the ManageUsers permission to prevent conflict during the Summer 24 release when Freeze Users and Monitor Ussers are automatically added by this permission @mhussaincgi 
cc @NataliaNikishina

**Comment by NatashaNeumann** [comment]
I'm new to GitHub and don't know what this is or who you are.

**Comment by mhussaincgi** [comment]
> I'm new to GitHub and don't know what this is or who you are.

Thanks for being patience, Accidently assigned to yourself. Reassigned to correct user.

**Review by NataliaNikishina — APPROVED** [review]
@mhussaincgi Successfully validated the branch. Deployment item added to Build 2.2.0. Thank you!

**Review by NataliaNikishina — APPROVED** [review]
@mhussaincgi  Approved.

**Pull request merged**
