### PR TITLE
BCMOHAD-20262 / BCMOHAD-20097 Report type fix.

### PR DESCRIPTION
**Pull request by dcstuff**
# Description

Fix to Cases with Contact report type to remove absent fields.

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Review by lilianenassar-bib — APPROVED** [review]
Approved

**Review by cgijeffolsen — APPROVED** [review]
Update approved, thank you @dcstuff @lilianenassar-bib

**Review by cgijeffolsen — APPROVED** [review]
Conflict resolved. Approved, thank you @dcstuff @lilianenassar-bib

**Review by lilianenassar-bib — APPROVED** [review]
Approved

**Pull request merged**
