### PR TITLE
Bcmohad 5614

### PR DESCRIPTION
**Pull request by monikadhillon**
RX/MAR Change in Prod

**Components** -

1. **Three Custom fields** 
    Describe_Dose_of_Bupivacaine__c.field
    Bupivacaine_Sodium_Chloride_flush__c.field
    Time_for_Dose_of_Bupivacaine__c.field
2. **Form RX/MAR Layout**  
    These fields are below Rocuronium_sodium_chloride__c
3. **Permission Sets** 
    MAiD Analyst 
    MAiD Manager
    MAiD System Administrator

### CODE REVIEW

**Review by herman-ovodov-cgi — CHANGES_REQUESTED** [review]
Changes look acceptable. Please confirm if this is to go to main and be treated as a hotfix, or if this should go to dev and be treated as an enhancement.

**Review by herman-ovodov-cgi — CHANGES_REQUESTED** [review]
PR looks acceptable to me, however, it is recommended to remove it and creating a new one to go into Dev branch.

**Review by herman-ovodov-cgi — CHANGES_REQUESTED** [review]
Please perform Git Checkout Dev for MAiD Case Layout, post-package.xml, and sfdx-project.json.

**Comment by monikadhillon** [comment]
Git Checkout Dev for MAiD Case Layout, post-package.xml, and sfdx-project.json is **performed** on this branch. @herman-ovodov-cgi

**Review by herman-ovodov-cgi — CHANGES_REQUESTED** [review]
Please review and resolve conflicts

**Review by herman-ovodov-cgi — APPROVED** [review]

**Pull request merged**
